{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.sobixn.server",
    "module": "buildSrc",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "buildSrc-1.0-SNAPSHOT.jar",
          "url": "buildSrc-1.0-SNAPSHOT.jar",
          "size": 4100,
          "sha512": "da5accdae8c642ed66b32e1e1035f42904f5ba437959f57afc7814e32c0cbea2ebe85da0c5e3c5264eb7c7f4efa805104cef58915b10659fca4158a1d6ab5dbf",
          "sha256": "2f08254894bd59653094c552fdcdd9d81eab603d54ad3ec0f3e5c4e0fcb61499",
          "sha1": "82b0ab0dca4832c994dec91711fc89016d9f247c",
          "md5": "0bfdd6d5f5a23c31c53ec3fc00667c4b"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "buildSrc-1.0-SNAPSHOT.jar",
          "url": "buildSrc-1.0-SNAPSHOT.jar",
          "size": 4100,
          "sha512": "da5accdae8c642ed66b32e1e1035f42904f5ba437959f57afc7814e32c0cbea2ebe85da0c5e3c5264eb7c7f4efa805104cef58915b10659fca4158a1d6ab5dbf",
          "sha256": "2f08254894bd59653094c552fdcdd9d81eab603d54ad3ec0f3e5c4e0fcb61499",
          "sha1": "82b0ab0dca4832c994dec91711fc89016d9f247c",
          "md5": "0bfdd6d5f5a23c31c53ec3fc00667c4b"
        }
      ]
    }
  ]
}
